import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AudioContextProvider } from './context/AudioContext'
import './globals.css'
import Navbar from '@/components/navbar/navbar'
import GlobalAudioControl from '@/components/GlobalAudioControl/GlobalAudioControl'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AudioContextProvider>
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <GlobalAudioControl/>
        {children}
        </body>
    </html>
    </AudioContextProvider>
  )
}
